version: '3.7'

services: 
  #PHP Service
    app:
        build:
            args:
                user: ammar
                uid: 1000 
            context: ./api/
            dockerfile: Dockerfile
        container_name: streaming-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./api:/var/www
            - ./api/docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - streaming-video-network

  #Nginx service
    webserver:
        image: nginx:alpine
        container_name: streaming-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
            # - "8143:443"
        volumes: 
            - ./api:/var/www
            - ./nginx/conf.d:/etc/nginx/template
            # - ./api/nginx/conf.d/:/etc/nginx/conf.d/
        #   - ./api/nginx/ssl/:/etc/nginx/ssl/
        networks:
            - streaming-video-network

  #MYSQL service
    db:
        image: mysql:5.7.22
        container_name: streaming-db
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            # - ./api/mysql/:/docker-entrypoint-initdb.d
        networks:
            - streaming-video-network


#Docker Networks
networks:
    streaming-video-network:
        driver: bridge

#Volumes
volumes: 
  dbdata:
        driver: local   